image: evolvingweb/drupal-fpm:ci-8.1
# Uncomment the following lines if you need a full Drupal.
#services:
#  - mariadb:10.5

stages:
  - build
  - deploy

variables:
  THEME_DIR: docroot/themes/custom/nobs_glider
  BLT: ./vendor/bin/blt
  BLT_DIR: ./vendor/acquia/blt
  DRUPAL_CI_DIR: ./vendor/evolvingweb/drupal-ci
  SCRIPTS_DIR: ./scripts
  MYSQL_DATABASE: drupal
  MYSQL_ROOT_PASSWORD: drupal
  SYNC_REPOSITORY: git@it.github.gatech.edu:honors-program/gt-honors.git

cache:
  paths:
    - $THEME_DIR/node_modules
    - .composer-cache/

sync_repo:
  stage: build
  script:
    - $SCRIPTS_DIR/ssh_key_add
    - $SCRIPTS_DIR/composer_install
    - $BLT validate
    - $BLT source:build --ansi --verbose --no-interaction
  only:
    - master
    - deploy
    - dev
    - release

build:
  stage: build
  script:
    - $SCRIPTS_DIR/ssh_key_add
    - $SCRIPTS_DIR/composer_install
    - $BLT validate
    - $BLT source:build --ansi --verbose --no-interaction

deploy_branch:
  stage: deploy
  script:
    - $SCRIPTS_DIR/ssh_key_add
    - $SCRIPTS_DIR/composer_install
    - $SCRIPTS_DIR/deploy_branch
  only:
    - branches
  except:
    - staging

deploy_tag:
  stage: deploy
  script:
    - $DRUPAL_CI_DIR/scripts/ssh_key_add
    - $DRUPAL_CI_DIR/scripts/deploy_tag
  only:
    - tags

deploy_staging:
  stage: deploy
  script:
    - $DRUPAL_CI_DIR/scripts/ssh_key_add
    - scripts/deploy_artifact
  only:
    - staging

validate_prod:
  stage: deploy
  script:
    - $DRUPAL_CI_DIR/scripts/ssh_key_add
    - $DRUPAL_CI_DIR/acquia/validate-prod-clean
  only:
    - tags
