#!/usr/bin/env bash

set -ev

composer config -g cache-dir "$(pwd)/.composer-cache"
composer self-update --2
composer validate --no-check-all --ansi
composer install
source ~/.bashrc
cd $CI_PROJECT_DIR

set +v
