name: Sync Repository From Gitlab

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

env:
  SOURCE_REPOSITORY: git@gitlab.ewdev.ca:evolvingweb/georgia-tech/gt-honors.git

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Sync Repository
      run: |
        git config remote.source.url >&- || git remote add source $SOURCE_REPOSITORY
        git remote -v
        git checkout source ${GITHUB_REF_NAME}
        git push origin ${GITHUB_REF_NAME}
